pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t my_react_app .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run --rm my_react_app npm test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker tag my_react_app:latest my_registry/my_react_app:latest'
                withCredentials([usernamePassword(credentialsId: 'my_registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD my_registry'
                    sh 'docker push my_registry/my_react_app:latest'
                }
            }
        }
    }
}